<?php
// $Id$

/**
 * @file
 * Demonstrates use of the Form API.
 *
 * For a full list of elements and attributes, see:
 * http://api.drupal.org/api/drupal/developer--topics--forms_api_reference.html/7
 */

/**
 * Implements hook_menu().
 */
function input_menu() {
  $items['input/examples'] = array(
    'title' => 'Form API examples',
    'description' => 'Example of using the sdfForm API.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('input_simple_form'),
    'access callback' => TRUE,
  );
  return $items;
}

sdfsdf
/**
 * A simple form.
 */
function input_simple_form($form, &$form_submit) {
  $form['color'] = array(
    '#title' => t('Favoritdfsafasdffffffffffffffffffffffffffffffffffe color'),
    '#type' => 'textfield',
    '#required' => TRUE,bbbbbbbbbbbbbbb
    '#description' => t('What is your favorite color? Blue? No, wait-'),
  );
  $form['submit'] = array(
    '#type' => 'submit',sdfsdfsdf
    '#value' => 'Submit',
  );
  return $form;asdf
}